spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: 13.125.222.209:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic-name:
      order-save : order-save


